package com.stackroute.springbootdynamodbcrud.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "persons")
public class Person {

    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute
    String id;

    @DynamoDBHashKey
    String email;

    @DynamoDBAttribute
    String name;

    @DynamoDBAttribute
    int age;

    public Person() {
    }


    public Person(String id,String email, String name, int age) {
        this.id = id;
        this.email = email;
        this.name = name;
        this.age = age;
    }

    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }


    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }



    public String toString() {
        return "Person Name:"+name+" Email:"+email+" age:"+age;
    }
}
